services:
  rdtclient:
    image: rogerfar/rdtclient:latest
    container_name: rdtclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    ports:
      - "6500:6500"
    volumes:
      - rdtclient_config:/data/db
      - "/mnt/downloads/debrid-link:/data"
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - UMASK=002
    ports:
      - "9696:9696"
    volumes:
      - prowlarr_config:/config
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - UMASK=002
    ports:
      - "7878:7878"
    volumes:
      - radarr_config:/config
      - "/mnt/downloads/debrid-link:/data"
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - UMASK=002
    ports:
      - "8989:8989"
    volumes:
      - sonarr_config:/config
      - "/mnt/downloads/debrid-link:/data"
    restart: unless-stopped

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - UMASK=002
    ports:
      - "5055:5055"
    volumes:
      - overseerr_config:/config
    restart: unless-stopped
  
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/Brussels
    ports:
      - "8191:8191"
    restart: unless-stopped

  clubnzb-proxy:
    build: ./clubnzb-proxy
    container_name: clubnzb-proxy
    environment:
      - TZ=Europe/Brussels
    ports:
      - "5080:5080"
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - UMASK=002
    ports:
      - "8080:8080"
    volumes:
      - sabnzbd_config:/config
      - "/mnt/downloads/debrid-link:/data"
    restart: unless-stopped

volumes:
  rdtclient_config:
  prowlarr_config:
  radarr_config:
  sonarr_config:
  overseerr_config:
  sabnzbd_config:
